/** Auto-generated by npm run gallery:sync — do not edit filenames by hand */
export type GalleryImage = {
  src: string;
  alt: string;
};

const GALLERY_FILENAMES = [
  "Screenshot 2026-05-22 001220.png",
  "Screenshot 2026-05-22 001230.png",
  "Screenshot 2026-05-22 001302.png",
  "Screenshot 2026-05-22 001331.png",
  "Screenshot 2026-05-22 001333.png",
  "Screenshot 2026-05-22 001334.png",
  "Screenshot 2026-05-22 001400.png",
  "Screenshot 2026-05-22 001938.png",
  "Screenshot 2026-05-22 002004.png",
  "Screenshot 2026-05-22 002034.png",
  "Screenshot 2026-05-22 002101.png",
] as const;

export const GALLERY_IMAGE_COUNT = GALLERY_FILENAMES.length;

export const galleryImages: GalleryImage[] = GALLERY_FILENAMES.map(
  (filename, i) => ({
    src: `/gallery/${encodeURIComponent(filename)}`,
    alt:
      i === 0
        ? "Shubham & Aishwarya — Together Forever"
        : `Wedding memory ${i + 1}`,
  })
);
