/**
 * Scans public/gallery and updates src/lib/gallery-images.ts + manifest.json
 * Run: npm run gallery:sync
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const galleryDir = path.join(root, "public", "gallery");
const outFile = path.join(root, "src", "lib", "gallery-images.ts");
const manifestFile = path.join(galleryDir, "manifest.json");

const IMAGE_EXT = /\.(jpe?g|png|webp)$/i;

/** Skip stock placeholders and removed photos */
const EXCLUDED = new Set([
  "photo-1.jpg",
  "photo-2.jpg",
  "photo-3.jpg",
  "photo-4.jpg",
  "photo_2026-05-21_23-36-32.jpg",
  "manifest.json",
]);

function sortGalleryFiles(files) {
  const numbered = files
    .filter((f) => /^photo_\d+_/.test(f))
    .sort(
      (a, b) =>
        parseInt(a.match(/photo_(\d+)_/)[1], 10) -
        parseInt(b.match(/photo_(\d+)_/)[1], 10)
    );
  const stamped = files
    .filter((f) => /^photo_\d{4}-\d{2}-\d{2}_/.test(f))
    .sort();
  const other = files
    .filter(
      (f) =>
        !/^photo_\d+_/.test(f) && !/^photo_\d{4}-\d{2}-\d{2}_/.test(f)
    )
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  return [...numbered, ...stamped, ...other];
}

function buildImageList(files) {
  return files.map((filename, i) => ({
    src: `/gallery/${encodeURIComponent(filename)}`,
    alt:
      i === 0
        ? "Shubham & Aishwarya — Together Forever"
        : `Wedding memory ${i + 1}`,
  }));
}

function hasExistingImages(filePath) {
  if (!fs.existsSync(filePath)) return false;
  const text = fs.readFileSync(filePath, "utf8");
  return /"[^"]+\.(jpe?g|png|webp)"/i.test(text);
}

function run() {
  const all = fs
    .readdirSync(galleryDir)
    .filter(
      (f) =>
        IMAGE_EXT.test(f) && !EXCLUDED.has(f) && !/^photo-\d+\.jpg$/i.test(f)
    );
  const files = sortGalleryFiles(all);

  if (files.length === 0) {
    console.warn(
      "No images in public/gallery/. Add JPG/PNG/WebP files, then run gallery:sync again."
    );
    if (hasExistingImages(outFile) || hasExistingImages(manifestFile)) {
      console.warn(
        "Keeping your previous gallery list (folder may be empty while OneDrive is syncing)."
      );
      process.exitCode = 1;
      return;
    }
  }

  const images = buildImageList(files);
  const list = files.map((f) => `  "${f}",`).join("\n");

  const content = `/** Auto-generated by npm run gallery:sync — do not edit filenames by hand */
export type GalleryImage = {
  src: string;
  alt: string;
};

const GALLERY_FILENAMES = [
${list}
] as const;

export const GALLERY_IMAGE_COUNT = GALLERY_FILENAMES.length;

export const galleryImages: GalleryImage[] = GALLERY_FILENAMES.map(
  (filename, i) => ({
    src: \`/gallery/\${encodeURIComponent(filename)}\`,
    alt:
      i === 0
        ? "Shubham & Aishwarya — Together Forever"
        : \`Wedding memory \${i + 1}\`,
  })
);
`;

  fs.writeFileSync(outFile, content, "utf8");
  fs.writeFileSync(
    manifestFile,
    JSON.stringify({ images, updatedAt: new Date().toISOString() }, null, 2),
    "utf8"
  );
  console.log(
    `Gallery sync: ${files.length} images → ${outFile} + manifest.json`
  );
}

run();
